source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HappyShop' do
  pod 'Alamofire', '3.0.0'
  pod 'AlamofireImage', '2.0.0'
  pod 'MBProgressHUD', '~> 0.9.2'
  
end

target 'HappyShopTests' do

end

